services:
  anylist:
    build:
      context: .
      target: development
    container_name: anylist-dev
    restart: unless-stopped
    volumes:
      # Mount source code for development
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Port forwarding for future web interface or API
    ports:
      - "3000:3000"
    # Health check
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # For development convenience
    stdin_open: true
    tty: true

  # Production service configuration
  anylist-prod:
    build:
      context: .
      target: production
    container_name: anylist-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Health check
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    profiles:
      - production

# Optional: Network configuration for future microservices
networks:
  default:
    name: anylist-network
    driver: bridge

# Optional: Volume for persistent data
volumes:
  anylist-data:
    driver: local